#!/usr/bin/env zsh
# lazy-load rbenv
rbenv() {
  if [[ -d '/usr/local/opt/rbenv' ]]; then
    export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
    eval "$(command rbenv init -)"
    # invoke the real nvm function now
    rbenv "$@"
  else
    echo "rbenv is not installed" >&2
    return 1
  fi
}
