# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/Dropbox/Apps/Dotfiles/zsh/custom"

export PATH="/Users/mrosales/pebble-dev/PebbleSDK-current/bin:/Users/mrosales/arm-cs-tools/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

plugins=(git brew autojump heroku sublime pebble)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
export EDITOR='vim'

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"
